import { useEffect, useMemo, useState } from 'react';
import { ClipboardCheck, Database, FileUp, LayoutDashboard, RefreshCw, Settings2, AlertTriangle, CheckCircle2 } from 'lucide-react';
import * as XLSX from 'xlsx';

type Product={id:string;name:string;catalogueName:string;type:string;uom:string;aliases?:string[];moleculeName?:string;hsn?:string;registrationStatus?:string};
type Row={productId:string|null;product:string;ourInward:number;ourOutward:number;ourClosing:number|null;openingStock:number|null;todayInward:number;todayOutward:number;warehouseInward:number;warehouseOutward:number;warehouseClosing:number|null;variance:number|null;status:string};
type Summary={productsChecked:number;matched:number;variance:number;pending:number;openingRequired:number;unmapped:number;positiveVariance:number;negativeVariance:number};
type SourceHealth={domesticRows:number;domesticInwardRows:number;domesticMin:string|null;domesticMax:string|null;outwardRows:number;outwardMin:string|null;outwardMax:string|null;warehouseRows:number;priorWarehouseDates:string[];inwardRowsToDate:number;outwardRowsToDate:number};
const api={
  async get(url:string){
    const r=await fetch(url);
    const data=await r.json().catch(()=>({}));
    if(!r.ok) throw new Error(data.error||'Request failed');
    return {data};
  },
  async post(url:string,body:unknown){
    const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
    const raw=await r.text();
    let data:any={};
    try{data=raw?JSON.parse(raw):{}}catch{}
    if(!r.ok) throw new Error(data.error||('Request failed ('+r.status+'): '+raw.slice(0,180)));
    return {data};
  }
};
const fmt=(v:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(v);
const today=new Date().toISOString().slice(0,10);
function parseCSV(text:string){const out:string[][]=[];let row:string[]=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],nx=text[i+1];if(c==='"'){if(q&&nx==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))out.push(row);row=[];}else cell+=c;}row.push(cell);if(row.some(x=>x.trim()))out.push(row);return out}
const headers=(r:string[])=>r.map(x=>x.trim().toLowerCase().replace(/[^a-z0-9]+/g,' '));
const find=(h:string[],names:string[])=>h.findIndex(x=>names.some(n=>x===n||x.includes(n)));
const num=(v:any)=>Number(String(v??'').replace(/,/g,'').replace(/[^\d.-]/g,''))||0;
const dateNorm=(v:any)=>{if(v instanceof Date&&!Number.isNaN(v.getTime()))return v.toISOString().slice(0,10);const s=String(v??'').trim();if(!s)return '';if(/^\d{4}-\d{1,2}-\d{1,2}/.test(s)){const m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/)!;return `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;}const m=s.match(/^(\d{1,2})[\\/-](\d{1,2})[\\/-](\d{4})/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;if(/^\d+(\.\d+)?$/.test(s)){const n=Number(s);if(n>30000&&n<60000){const d=new Date(Date.UTC(1899,11,30)+n*86400000);return d.toISOString().slice(0,10);}}const d=new Date(s);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)};

function App(){
 const [products,setProducts]=useState<Product[]>([]),[view,setView]=useState('report'),[date,setDate]=useState(today),[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Summary|null>(null),[sourceHealth,setSourceHealth]=useState<SourceHealth|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[mappingSource,setMappingSource]=useState('Domestic MIS'),[mappingName,setMappingName]=useState(''),[candidates,setCandidates]=useState<any[]>([]),[mappingProduct,setMappingProduct]=useState('');
 const nav=[['report','EOD Inventory Report',ClipboardCheck],['reconciliation','Daily Reconciliation',AlertTriangle],['overview','Control Overview',LayoutDashboard],['masters','Product Catalogue',Database],['import','Daily Data Import',FileUp],['mapping','Source Mapping',Settings2]] as const;
 async function reconcile(){setLoading(true);try{const r=await api.get('/api/reconciliation?date='+encodeURIComponent(date));setRows(r.data.rows||[]);setSummary(r.data.summary||null);setSourceHealth(r.data.sourceHealth||null)}finally{setLoading(false)}}
 async function load(){const r=await api.get('/api/inventory');setProducts(r.data.products||[]);await reconcile()}
 useEffect(()=>{load()},[]);useEffect(()=>{reconcile()},[date]);
 async function importFile(source:string,file:File){
  let matrix:string[][];
  if(/\.xlsx?$/i.test(file.name)){
   const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,cellNF:false,cellText:false});
   if(source==='Warehouse Report'){
    let found:string[][]|null=null;
    for(const sheetName of wb.SheetNames){
     const candidate=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,raw:true,defval:''}) as string[][];
     const hasHeader=candidate.some(r=>{const z=headers(r);return z.some(x=>x.includes('material description'))&&(z.some(x=>x.includes('physical closing stock'))||z.some(x=>x.includes('stock in hand'))||z.some(x=>x.includes('physical stock'))||z.some(x=>x.includes('closing stock')))});
     if(hasHeader){found=candidate;break}
    }
    if(!found)throw new Error('No Stock in Hand sheet found. Expected Material Description and Physical Closing Stock/Closing Stock columns.');
    matrix=found;
   }else{
    const ws=wb.Sheets[wb.SheetNames[0]];
    matrix=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:''}) as string[][];
   }
  }else{
   matrix=parseCSV(await file.text());
  }
  if(matrix.length<2)throw new Error('File is empty.');
  const h=headers(matrix[0]),data=matrix.slice(1);
  if(source==='Product Catalogue'){const ci=find(h,['product catalogue name']);if(ci<0)throw new Error('Product Catalogue Name column not found.');const ai=find(h,['product name']),mi=find(h,['molecule name']),ti=find(h,['technical formulation','technical / formulation']),hi=find(h,['hsn']),ri=find(h,['registeration status','registration status']);const map=new Map<string,any>();for(const r of data){const cat=String(r[ci]||'').trim();if(!cat)continue;let x=map.get(cat);if(!x){x={catalogueName:cat,aliases:[],moleculeName:mi>=0?r[mi]||'':'',technicalFormulation:ti>=0?r[ti]||'':'',hsn:hi>=0?r[hi]||'':'',registrationStatus:ri>=0?r[ri]||'':''};map.set(cat,x)}if(ai>=0&&r[ai])x.aliases.push(String(r[ai]).trim())}const r=await api.post('/api/catalogue/import',{rows:Array.from(map.values())});setNotice('Catalogue imported: '+(r.data.added||0)+' added, '+(r.data.updated||0)+' updated.');await load();return}
  if(source==='Domestic MIS'){const headerAt=matrix.findIndex(r=>{const z=headers(r);return (z.some(x=>x.includes('ib ob date'))||z.some(x=>x.includes('inward date'))||z.some(x=>x.includes('arrival date')))&&(z.some(x=>x.includes('ag catalogue name'))||z.some(x=>x==='product name')||z.some(x=>x==='product'))&&(z.some(x=>x.includes('qty kg'))||z.some(x=>x.includes('net weight kg'))||z.some(x=>x.includes('net weight'))||z.some(x=>x==='qty'))});if(headerAt<0)throw new Error('Could not find the Domestic MIS header row. Expected date, product and quantity columns.');const dh=headers(matrix[headerAt]),dd=matrix.slice(headerAt+1);const di=find(dh,['ib ob date','inward date','arrival date']),pi=find(dh,['ag catalogue name','product name','product']),qi=find(dh,['qty kg','net weight kg','net weight','qty']),ty=find(dh,['type','movement type','ib ob']);if(di<0||pi<0||qi<0)throw new Error('Expected a movement date, product and quantity column in the Domestic MIS.');const hasType=ty>=0;const rows=dd.map(r=>({movementDate:dateNorm(r[di]),productName:String(r[pi]||'').trim(),quantity:num(r[qi]),direction:hasType?( /^(inward|ib|inbound|receipt|grn)$/i.test(String(r[ty]||'').trim())?'INWARD':/^(outward|ob|outbound|dispatch)$/i.test(String(r[ty]||'').trim())?'OUTWARD':''):'INWARD'})).filter(r=>r.movementDate&&r.productName&&r.quantity>0&&r.direction==='INWARD');if(!rows.length)throw new Error('No valid inward rows found in the Domestic MIS. Header was detected, but no inward rows were recognised. Check the Type column values.');const r=await api.post('/api/source-import',{source,reportDate:date,rows});const dates=rows.map(x=>x.movementDate).sort();setNotice('Domestic MIS imported: '+r.data.inserted+' actual inward rows · '+dates[0]+' to '+dates[dates.length-1]+'.');await reconcile();setView('reconciliation');return}
  if(source==='Outward Dispatch Sheet'){const headerAt=matrix.findIndex(r=>{const z=headers(r);return z.some(x=>x.includes('dispatch date'))&&z.some(x=>x.includes('product'))&&z.some(x=>x.includes('total weight'))});if(headerAt<0)throw new Error('Could not find the Outward Dispatch header row. Expected Dispatch Date, Product and Total Weight columns.');const oh=headers(matrix[headerAt]),od=matrix.slice(headerAt+1);const di=find(oh,['dispatch date']),pi=find(oh,['product']),qi=find(oh,['total weight']);if(di<0||pi<0||qi<0)throw new Error('Expected Dispatch Date, Product and Total Weight columns.');const rows=od.map(r=>({movementDate:dateNorm(r[di]),productName:String(r[pi]||'').trim(),quantity:num(r[qi]),direction:'OUTWARD'})).filter(r=>r.movementDate&&r.productName&&r.quantity>0);if(!rows.length)throw new Error('No valid outward rows found after detecting the dispatch header.');const rr=await api.post('/api/source-import',{source,reportDate:date,rows});const dates=rows.map(x=>x.movementDate).sort();setNotice('Outward Dispatch Sheet imported: '+rr.data.inserted+' actual dispatch rows · '+dates[0]+' to '+dates[dates.length-1]+'.');await reconcile();setView('reconciliation');return}
  if(source==='Warehouse Report'){
   const headerAt=matrix.findIndex(r=>{const z=headers(r);return z.some(x=>x.includes('material description'))&&(z.some(x=>x.includes('physical closing stock'))||z.some(x=>x.includes('stock in hand'))||z.some(x=>x.includes('physical stock'))||z.some(x=>x.includes('closing stock')))});
   if(headerAt<0)throw new Error('Could not find the Warehouse Excel Stock in Hand header. Expected Material Description and Physical Closing Stock/Closing Stock columns.');
   const whH=headers(matrix[headerAt]),whData=matrix.slice(headerAt+1);
   const matName=find(whH,['material description'])>=0?find(whH,['material description']):find(whH,['product name','material name','item name']);const ii=find(whH,['qty received','material inbound','inbound kg','inbound']),oi=find(whH,['qty dispatched','outbound kg','outbound']),psi=find(whH,['physical closing stock']),shi=find(whH,['stock in hand']),phsi=find(whH,['physical stock']),csi=find(whH,['closing stock']);
   const si=psi>=0?psi:shi>=0?shi:phsi>=0?phsi:csi;
   if(matName<0||si<0)throw new Error('Expected Material Description and a warehouse stock column such as Physical Closing Stock, Stock in Hand, Physical Stock or Closing Stock in the Warehouse Excel.');
   const rows=whData.map(r=>({productName:String(r[matName]||'').trim(),warehouseInward:ii>=0?num(r[ii]):0,warehouseOutward:oi>=0?num(r[oi]):0,warehouseStock:num(r[si])})).filter(r=>r.productName);
   if(!rows.length)throw new Error('No warehouse stock rows found in the Stock in Hand sheet.');
   const rr=await api.post('/api/source-import',{source,reportDate:date,rows});
   setNotice('Warehouse Excel imported: '+rr.data.inserted+' stock rows for EOD '+date+'.');await reconcile();setView('reconciliation');return
  }
 }
 async function resolve(){const r=await api.post('/api/mappings/resolve',{source:mappingSource,sourceName:mappingName});setCandidates(r.data.candidates||[]);setMappingProduct(r.data.product?.id||'');setNotice(r.data.status==='AUTO'?'Automatic match found.':'Review the suggested catalogue match before saving.')}
 async function saveMap(){await api.post('/api/mappings',{source:mappingSource,sourceName:mappingName,productId:mappingProduct});setNotice('Source mapping saved.');setMappingName('');setCandidates([])}
 const variance=useMemo(()=>rows.filter(r=>r.status==='VARIANCE'),[rows]);
 return <div className="min-h-screen bg-slate-100 text-slate-900"><aside className="fixed left-0 top-0 bottom-0 w-64 bg-slate-950 text-white p-5 hidden md:block"><div className="text-xl font-bold">Atomgrid Inventory</div><div className="text-xs text-slate-400 mt-1">Daily stock control</div><div className="mt-8 space-y-1">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={'w-full flex items-center gap-3 px-3 py-3 rounded-lg text-sm '+(view===id?'bg-white text-slate-950':'text-slate-300 hover:bg-white/10')}><Icon size={17}/>{label}</button>)}</div></aside>
 <main className="md:ml-64 p-5 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><div className="text-sm text-slate-500">Atomgrid · Inventory Control</div><h1 className="text-2xl font-bold">{nav.find(x=>x[0]===view)?.[1]}</h1></div><div className="flex gap-2 items-center"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="bg-white border rounded-lg px-3 py-2"/><button onClick={reconcile} className="bg-white border rounded-lg p-2"><RefreshCw size={17}/></button></div></div>{notice&&<div className="mb-4 bg-white border rounded-lg p-3 text-sm">{notice}</div>}
 {view==='report'&&<EodReport date={date} rows={rows} summary={summary} loading={loading}/>}
 {view==='reconciliation'&&<div className="space-y-5">{summary&&<div className="grid grid-cols-2 md:grid-cols-6 gap-3">{[['Products checked',summary.productsChecked],['Matched',summary.matched],['Variance',summary.variance],['Pending',summary.pending],['Opening Required',summary.openingRequired],['Unmapped',summary.unmapped]].map(([a,b])=><div className="bg-white border rounded-xl p-4" key={String(a)}><div className="text-xs text-slate-500">{a}</div><div className="text-2xl font-bold mt-1">{b}</div></div>)}</div>}<div className="bg-white border rounded-xl p-5"><div className="mb-4"><h2 className="font-bold">Daily Stock Reconciliation</h2><p className="text-sm text-slate-500 mt-1">Our EOD = previous verified warehouse closing + actual inward today − actual outward today. This prevents the report from assuming the warehouse started at zero.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{['Product','Opening','Today Inward','Today Outward','Our Closing','WH Closing','Variance','Status'].map(x=><th className="p-3 text-left whitespace-nowrap" key={x}>{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} className="p-10 text-center text-slate-400">Checking stock…</td></tr>:rows.map(r=><tr className="border-t" key={r.product}><td className="p-3 font-semibold">{r.product}</td><td className="p-3">{r.openingStock==null?'—':fmt(r.openingStock)}</td><td className="p-3">{fmt(r.todayInward)}</td><td className="p-3">{fmt(r.todayOutward)}</td><td className="p-3 font-semibold">{r.ourClosing==null?'—':fmt(r.ourClosing)}</td><td className="p-3">{r.warehouseClosing==null?'—':fmt(r.warehouseClosing)}</td><td className={'p-3 font-bold '+(r.variance&&r.variance!==0?'text-red-600':'text-emerald-600')}>{r.variance==null?'—':fmt(r.variance)}</td><td className="p-3"><span className={'inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-semibold '+(r.status==='MATCH'?'bg-emerald-50 text-emerald-700':r.status==='VARIANCE'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700')}>{r.status==='MATCH'?<CheckCircle2 size={13}/>:<AlertTriangle size={13}/>} {r.status}</span></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-400">No source data imported for this date.</td></tr>}</tbody></table></div></div></div>}
 {view==='overview'&&<div className="space-y-5"><div className="bg-white border rounded-xl p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold">Daily Control Center</h2><p className="text-sm text-slate-500 mt-1">Selected EOD: {date}. Resolve every red, amber or unmapped row before publishing the report.</p></div><button onClick={reconcile} className="bg-slate-900 text-white rounded-lg px-4 py-2 text-sm font-semibold">Run Daily Check</button></div></div><div className="grid md:grid-cols-3 gap-4"><div className="bg-white border rounded-xl p-5"><div className="text-sm text-slate-500">Matched products</div><div className="text-3xl font-bold mt-2">{summary?.matched||0}</div></div><div className="bg-white border rounded-xl p-5"><div className="text-sm text-slate-500">Positive / negative variance</div><div className="text-3xl font-bold mt-2">{fmt(summary?.positiveVariance||0)} / {fmt(summary?.negativeVariance||0)}</div></div><div className="bg-white border rounded-xl p-5"><div className="text-sm text-slate-500">Products needing action</div><div className="text-3xl font-bold mt-2">{variance.length+(summary?.unmapped||0)+(summary?.pending||0)+(summary?.openingRequired||0)}</div></div></div>{sourceHealth&&<div className="bg-white border rounded-xl p-5"><h3 className="font-bold">Source Data Health</h3><div className="grid md:grid-cols-4 gap-3 mt-3 text-sm"><div><div className="text-slate-500">Domestic MIS</div><b>{sourceHealth.domesticInwardRows}</b> inward rows · {sourceHealth.domesticMin||'—'} to {sourceHealth.domesticMax||'—'}</div><div><div className="text-slate-500">Outward Dispatch</div><b>{sourceHealth.outwardRows}</b> rows · {sourceHealth.outwardMin||'—'} to {sourceHealth.outwardMax||'—'}</div><div><div className="text-slate-500">Warehouse EOD</div><b>{sourceHealth.warehouseRows}</b> rows for {date}</div><div><div className="text-slate-500">Movements to EOD</div><b>{sourceHealth.inwardRowsToDate}</b> inward · <b>{sourceHealth.outwardRowsToDate}</b> outward</div></div>{sourceHealth.priorWarehouseDates.length===0&&<div className="mt-3 text-amber-700 bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm">No earlier warehouse EOD is loaded. Import the previous EOD warehouse report so the system can calculate opening stock correctly.</div>}</div>}</div>}
 {view==='masters'&&<div className="space-y-5"><div className="bg-white border rounded-xl p-5"><h2 className="font-bold">Product Catalogue — source of truth</h2><p className="text-sm text-slate-500 mt-1">Product Catalogue Name is the canonical identity. Product Name variants are retained as aliases.</p></div><div className="bg-white border rounded-xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Canonical Product</th><th className="p-3 text-left">Molecule</th><th className="p-3 text-left">HSN</th><th className="p-3 text-left">Registration</th><th className="p-3 text-left">Aliases</th></tr></thead><tbody>{products.map(p=><tr className="border-t" key={p.id}><td className="p-3 font-semibold">{p.catalogueName}</td><td className="p-3">{p.moleculeName||'—'}</td><td className="p-3">{p.hsn||'—'}</td><td className="p-3">{p.registrationStatus||'—'}</td><td className="p-3 text-slate-500">{(p.aliases||[]).slice(0,5).join(', ')||'—'}</td></tr>)}</tbody></table></div></div>}
 {view==='mapping'&&<div className="bg-white border rounded-xl p-5 max-w-3xl"><h2 className="font-bold">Source → Product Catalogue Mapping</h2><p className="text-sm text-slate-500 mt-1">Use this when automatic alias matching is not confident enough.</p><div className="grid md:grid-cols-3 gap-3 mt-5"><select value={mappingSource} onChange={e=>setMappingSource(e.target.value)} className="border rounded-lg px-3 py-2"><option>Domestic MIS</option><option>Outward Dispatch Sheet</option><option>Warehouse Report</option></select><input value={mappingName} onChange={e=>setMappingName(e.target.value)} placeholder="Exact source product name" className="border rounded-lg px-3 py-2 md:col-span-2"/></div><div className="flex gap-2 mt-3"><button onClick={resolve} className="border rounded-lg px-4 py-2 font-semibold">Find match</button><button onClick={saveMap} disabled={!mappingProduct} className="bg-slate-900 text-white rounded-lg px-4 py-2 font-semibold disabled:opacity-40">Save mapping</button></div>{candidates.length>0&&<div className="mt-4 space-y-2">{candidates.map(c=><button key={c.product.id} onClick={()=>setMappingProduct(c.product.id)} className={'w-full text-left border rounded-lg p-3 '+(mappingProduct===c.product.id?'border-cyan-500 bg-cyan-50':'')}><b>{c.product.catalogueName||c.product.name}</b><div className="text-xs text-slate-500">{Math.round(c.score*100)}% match</div></button>)}</div>}</div>}
 {view==='import'&&<ImportPanel onImport={importFile} date={date}/>}
 </main></div>
}
function EodReport({date,rows,summary,loading}:{date:string;rows:Row[];summary:Summary|null;loading:boolean}){
 const [section,setSection]=useState<'summary'|'shipments'|'warehouse'>('summary');
 const totalOur=rows.reduce((s,r)=>s+(r.ourClosing==null?0:r.ourClosing),0), totalWh=rows.reduce((s,r)=>s+(r.warehouseClosing||0),0), totalVar=rows.reduce((s,r)=>s+(r.variance||0),0);
 const titleDate=date?(()=>{const [y,m,d]=date.split('-');return `${d}/${m}/${y}`})():'';
 return <div className="space-y-4">
  <div className="bg-white border rounded-xl overflow-hidden">
   <div className="bg-orange-200 px-5 py-3 text-center font-bold">Inventory Report Date EOD Till {titleDate}</div>
   <div className="grid md:grid-cols-4 border-b text-sm font-semibold">
    <div className="p-3 bg-emerald-50">AG Warehouse (Panoli)</div><div className="p-3">AG MIS Sheet — Overall Summary Till Date</div><div className="p-3">Shipments on {titleDate}</div><div className="p-3">MIS Report Panoli — From Warehouse</div>
   </div>
   <div className="flex gap-1 p-2 bg-slate-50 border-b">
    {([['summary','Overall Summary'],['shipments','Shipments Today'],['warehouse','Warehouse Verification']] as const).map(([id,label])=><button key={id} onClick={()=>setSection(id)} className={'px-3 py-2 rounded-lg text-xs font-semibold '+(section===id?'bg-slate-900 text-white':'bg-white border')}>{label}</button>)}
   </div>
   {loading?<div className="p-12 text-center text-slate-400">Preparing EOD report…</div>:
   <div className="overflow-x-auto"><table className="w-full text-xs min-w-[900px]"><thead className="bg-slate-100"><tr>
    {section==='summary'&&<><th className="p-2 text-left">Product Name</th><th className="p-2 text-right">Inbound Till Date</th><th className="p-2 text-right">Outbound Till Date</th><th className="p-2 text-right">Our Instock</th><th className="p-2 text-right">WH Instock</th><th className="p-2 text-right">Variance</th><th className="p-2 text-left">Status</th></>}
    {section==='shipments'&&<><th className="p-2 text-left">Product Name</th><th className="p-2 text-right">Inbound {titleDate}</th><th className="p-2 text-right">Outbound {titleDate}</th><th className="p-2 text-right">Net Movement</th></>}
    {section==='warehouse'&&<><th className="p-2 text-left">Product Name</th><th className="p-2 text-right">WH Inbound</th><th className="p-2 text-right">WH Outbound</th><th className="p-2 text-right">WH Instock</th><th className="p-2 text-right">Our Instock</th><th className="p-2 text-right">Variance</th><th className="p-2 text-left">Status</th></>}
   </tr></thead><tbody>
   {rows.map(r=><tr key={r.product} className="border-t hover:bg-slate-50">
    <td className="p-2 font-medium">{r.product}</td>
    {section==='summary'&&<><td className="p-2 text-right">{fmt(r.ourInward)}</td><td className="p-2 text-right">{fmt(r.ourOutward)}</td><td className="p-2 text-right font-semibold">{r.ourClosing==null?'—':fmt(r.ourClosing)}</td><td className="p-2 text-right">{r.warehouseClosing==null?'—':fmt(r.warehouseClosing)}</td><td className={'p-2 text-right font-bold '+((r.variance||0)!==0?'text-red-600':'text-emerald-600')}>{r.variance==null?'—':fmt(r.variance)}</td><td className="p-2">{r.status}</td></>}
    {section==='shipments'&&<><td className="p-2 text-right">{r.todayInward?fmt(r.todayInward):'—'}</td><td className="p-2 text-right">{r.todayOutward?fmt(r.todayOutward):'—'}</td><td className="p-2 text-right font-semibold">{fmt(r.todayInward-r.todayOutward)}</td></>}
    {section==='warehouse'&&<><td className="p-2 text-right">{fmt(r.warehouseInward)}</td><td className="p-2 text-right">{fmt(r.warehouseOutward)}</td><td className="p-2 text-right">{r.warehouseClosing==null?'—':fmt(r.warehouseClosing)}</td><td className="p-2 text-right font-semibold">{fmt(r.ourClosing)}</td><td className={'p-2 text-right font-bold '+((r.variance||0)!==0?'text-red-600':'text-emerald-600')}>{r.variance==null?'—':fmt(r.variance)}</td><td className="p-2">{r.status}</td></>}
   </tr>)}{!rows.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-400">No data for this EOD date.</td></tr>}</tbody></table></div>}
  </div>
  {summary&&<div className="grid grid-cols-2 md:grid-cols-6 gap-3">{[['Products',summary.productsChecked],['Matched',summary.matched],['Variance',summary.variance],['Pending',summary.pending],['Opening Required',summary.openingRequired],['Unmapped',summary.unmapped]].map(([a,b])=><div className="bg-white border rounded-xl p-4" key={String(a)}><div className="text-xs text-slate-500">{a}</div><div className="text-xl font-bold">{b}</div></div>)}</div>}
  <div className="bg-slate-900 text-white rounded-xl p-4 text-sm flex flex-wrap gap-5"><span>Our Closing: <b>{fmt(totalOur)} KG</b></span><span>Warehouse Closing: <b>{fmt(totalWh)} KG</b></span><span>Total Variance: <b>{fmt(totalVar)} KG</b></span></div>
 </div>
}
function ImportPanel({onImport,date}:{onImport:(s:string,f:File)=>Promise<void>;date:string}){const [busy,setBusy]=useState('');const items=[['Product Catalogue','Master catalogue CSV / Excel'],['Domestic MIS','Actual inward source — uses actual arrival date'],['Outward Dispatch Sheet','Actual outward source — uses actual dispatch date'],['Warehouse Report','Warehouse Excel — Stock in Hand / Physical Closing Stock']];return <div className="bg-white border rounded-xl p-5 max-w-3xl"><h2 className="font-bold">Daily source imports</h2><p className="text-sm text-slate-500 mt-1">Import source files; the system calculates our stock and cross-checks warehouse stock for the selected date.</p><div className="mt-5 space-y-3">{items.map(([s,d])=><label key={s} className="border rounded-xl p-4 flex items-center justify-between cursor-pointer hover:bg-slate-50"><div><div className="font-semibold">{s}</div><div className="text-xs text-slate-500">{d}{s!=='Product Catalogue'?' · report date '+date:''}</div></div><input type="file" accept={s==='Warehouse Report'?'.xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel':'.csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'} className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(s);try{await onImport(s,f)}catch(err:any){alert(err.message||'Import failed')}finally{setBusy('');e.currentTarget.value=''}}}/><span className="px-3 py-2 rounded-lg bg-slate-900 text-white text-xs">{busy===s?'Importing…':s==='Warehouse Report'?'Choose Excel':'Choose File'}</span></label>)}</div></div>}
export default App;